#mvn jasypt:encrypt -Djasypt.encryptor.password={PASSWORD} -Djasypt.plugin.path="file:src/main/resources/docker-compose.yaml"
#mvn jasypt:decrypt -Djasypt.encryptor.password={PASSWORD} -Djasypt.plugin.path="file:src/main/resources/docker-compose.yaml"
version: "3.8"
services:
  mongoservice:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    hostname: localhost
  demo_app:
    depends_on:
      - mongoservice
    build:
      dockerfile: Dockerfile
    image: demo_image
    ports:
      - "8085:8085"
    restart: on-failure
    links:
      - mongoservice
  mongodb-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongoservice
volumes:
  data: { }

networks:
  default:
    name: mongodb_network